apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ynxja33k7-go
  janus-idp.io/tekton: ynxja33k7-go
  backstage.io/kubernetes-id: ynxja33k7-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ynxja33k7-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
